#include <geos/version.h>

#include "functions.hpp"
#include "rowbinary.hpp"
#include "udf.hpp"

extern "C" {

CH_UDF_FUNC(geos_bench_noop)
CH_UDF_FUNC(geos_bench_noop_rb)
CH_UDF_FUNC(geos_bench_wkb_parse)
CH_UDF_FUNC(geos_bench_envelope)
CH_UDF_FUNC(geos_bench_intersects_nobbox)
CH_UDF_FUNC(geos_version)
CH_UDF_FUNC(st_astext)
CH_UDF_FUNC(st_asewkt)
CH_UDF_FUNC(st_geomfromtext)
CH_UDF_FUNC(st_geomfromgeojson)
CH_UDF_FUNC(st_extent)
CH_UDF_FUNC(st_intersects_extent)  // pure bbox, no GEOS
CH_UDF_RB_FUNC(st_intersects_extent)  // same logic, RowBinary serialization
CH_UDF_FUNC(st_x)
CH_UDF_FUNC(st_y)
CH_UDF_FUNC(st_centroid)
CH_UDF_FUNC(st_distance)
CH_UDF_FUNC(st_difference)
CH_UDF_FUNC(st_transform)
CH_UDF_FUNC(st_transform_proj)
CH_UDF_FUNC(st_translate)
CH_UDF_BBOX2(st_contains,   bbox_op_contains,   false)
CH_UDF_BBOX2(st_intersects, bbox_op_intersects, false)
CH_UDF_BBOX2(st_touches,    bbox_op_intersects, false)
CH_UDF_FUNC(st_area)
CH_UDF_FUNC(st_dwithin)
CH_UDF_FUNC(st_makevalid)
CH_UDF_FUNC(st_expand)
CH_UDF_FUNC(st_scale)
CH_UDF_FUNC(st_union)
CH_UDF_FUNC(st_subdivide)
CH_UDF_FUNC(st_npoints)
CH_UDF_FUNC(st_geomfromwkb)
CH_UDF_FUNC(st_startpoint)
CH_UDF_FUNC(st_endpoint)
CH_UDF_FUNC(st_envelope)
CH_UDF_FUNC(st_intersection)
CH_UDF_FUNC(st_clusterintersecting)
CH_UDF_FUNC(st_collect)
CH_UDF_FUNC(st_unaryunion)
CH_UDF_FUNC(st_union_agg)
CH_UDF_FUNC(st_collect_agg)
CH_UDF_FUNC(st_extent_agg)
CH_UDF_FUNC(st_makeline_agg)
CH_UDF_FUNC(st_convexhull_agg)
CH_UDF_FUNC(st_simplify)
CH_UDF_FUNC(st_buffer)
CH_UDF_FUNC(st_buffer_params)
CH_UDF_FUNC(st_segmentize)
CH_UDF_FUNC(st_makebox2d)
CH_UDF_FUNC(st_srid)
CH_UDF_FUNC(st_setsrid)
CH_UDF_FUNC(st_geomfromchpoint)
CH_UDF_FUNC(st_geomfromchlinestring)
CH_UDF_FUNC(st_geomfromchpolygon)
CH_UDF_FUNC(st_geomfromchmultipolygon)
// Predicates — bbox shortcut via with_bbox + pure GEOS _impl
CH_UDF_BBOX2(st_within,           bbox_op_rcontains,  false)
CH_UDF_BBOX2(st_crosses,          bbox_op_intersects, false)
CH_UDF_BBOX2(st_overlaps,         bbox_op_intersects, false)
CH_UDF_BBOX2(st_disjoint,         bbox_op_intersects, true)
CH_UDF_BBOX2(st_equals,           bbox_op_intersects, false)
CH_UDF_BBOX2(st_covers,           bbox_op_contains,   false)
CH_UDF_BBOX2(st_coveredby,        bbox_op_rcontains,  false)
CH_UDF_BBOX2(st_containsproperly, bbox_op_contains,   false)
CH_UDF_FUNC(st_relate)
CH_UDF_FUNC(st_relate_pattern)
// Accessors
CH_UDF_FUNC(st_length)
CH_UDF_FUNC(st_isvalid)
CH_UDF_FUNC(st_isempty)
CH_UDF_FUNC(st_issimple)
CH_UDF_FUNC(st_isring)
CH_UDF_FUNC(st_geometrytype)
CH_UDF_FUNC(st_numgeometries)
CH_UDF_FUNC(st_numinteriorrings)
CH_UDF_FUNC(st_numpoints)
CH_UDF_FUNC(st_dimension)
CH_UDF_FUNC(st_interiorpoint)
CH_UDF_FUNC(st_isvalidreason)
CH_UDF_FUNC(st_z)
CH_UDF_FUNC(st_nrings)
CH_UDF_FUNC(st_perimeter)
CH_UDF_FUNC(st_hausdorffdistance)
CH_UDF_FUNC(st_hausdorffdistance_densify)
CH_UDF_FUNC(st_frechetdistance)
CH_UDF_FUNC(st_frechetdistance_densify)
// Constructors / operations
CH_UDF_FUNC(st_convexhull)
CH_UDF_FUNC(st_boundary)
CH_UDF_FUNC(st_reverse)
CH_UDF_FUNC(st_normalize)
CH_UDF_FUNC(st_geometryn)
CH_UDF_FUNC(st_symdifference)
CH_UDF_FUNC(st_exteriorring)
CH_UDF_FUNC(st_interiorringn)
CH_UDF_FUNC(st_pointn)
CH_UDF_FUNC(st_minimumboundingcircle)
CH_UDF_FUNC(st_snap)
CH_UDF_FUNC(st_offsetcurve)
CH_UDF_FUNC(st_linmerge)
CH_UDF_FUNC(st_polygonize)
CH_UDF_FUNC(st_delaunaytriangles)
CH_UDF_FUNC(st_voronoidiagram)
CH_UDF_FUNC(st_makepoint)
CH_UDF_FUNC(st_makepoint3d)
CH_UDF_FUNC(st_makepolygon)
CH_UDF_FUNC(st_makeline)
CH_UDF_FUNC(st_closestpoint)
CH_UDF_FUNC(st_shortestline)
CH_UDF_FUNC(st_sharedpaths)
CH_UDF_FUNC(st_node)
CH_UDF_FUNC(st_addpoint)
CH_UDF_FUNC(st_removepoint)
CH_UDF_FUNC(st_setpoint)
CH_UDF_FUNC(geos_log_test)
CH_UDF_FUNC(geos_test_exception)

} // extern "C"
